### ISSUE TITLE
Compile error via esphome

### ISSUE THREAD

**Issue by jmerryman** [mikesmitty/esphome-components#1]
Attempting to build via esphome in Home Assistant, using example yaml. Appears that the relative reference to the "pioneer_wyt_protocol" isn't resolving. I'm not familiar enough with the build environment for esphome to suggest a fix

From yaml config:

external_components:
  - source: github://mikesmitty/esphome-components
    components: [ pioneer ]

===
Compiling .pioenvs/family-room-heat-pump/src/esphome/components/pioneer/wyt_climate.cpp.o
Compiling .pioenvs/family-room-heat-pump/src/esphome/components/safe_mode/safe_mode.cpp.o
In file included from src/esphome/components/pioneer/wyt_climate.h:4,
                 from src/esphome/components/pioneer/wyt_climate.cpp:1:
src/esphome/components/pioneer/wyt_remote.h:5:10: fatal error: esphome/components/remote_base/pioneer_wyt_protocol.h: No such file or directory
 #include "esphome/components/remote_base/pioneer_wyt_protocol.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/family-room-heat-pump/src/esphome/components/pioneer/wyt_climate.cpp.o] Error 1
========================== [FAILED] Took 3.20 seconds ==========================

**Comment by mikesmitty** [comment]
Oh, yep. I ended up adding a function to the built-in remote_base component for the follow-me function implementation and it can't be not compiled in at the moment. I'll update the docs here in a sec, but adding remote_base to the components list will fix it:
```
- source: github://mikesmitty/esphome-components
  components: [ pioneer, remote_base ]
```

**Comment by jmerryman** [comment]
Thanks for the quick reply - actually I had tried that last night. Just tried again (after cleaning build files) and get the same error

From YAML:
external_components:
  - source: github://mikesmitty/esphome-components
    components: [ pioneer, remote_base ]

compile log:

Compiling .pioenvs/family-room-heat-pump/src/esphome/components/pioneer/wyt_climate.cpp.o
In file included from src/esphome/components/pioneer/wyt_climate.h:4,
                 from src/esphome/components/pioneer/wyt_climate.cpp:1:
src/esphome/components/pioneer/wyt_remote.h:5:10: fatal error: esphome/components/remote_base/pioneer_wyt_protocol.h: No such file or directory
 #include "esphome/components/remote_base/pioneer_wyt_protocol.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/family-room-heat-pump/src/esphome/components/pioneer/wyt_climate.cpp.o] Error 1
========================= [FAILED] Took 25.89 seconds =========================

**Comment by mikesmitty** [comment]
That's odd, I wonder if it's caching an old copy of the repo. You might need to delete the external_components cache from the .esphome folder: `.esphome/external_components/`

**Comment by jmerryman** [comment]
Same issue with a fresh install of esphome command-line on my mac (using homebrew). 

Compiling .pioenvs/familyroom-heatpump/src/esphome/components/sensor/automation.cpp.o
In file included from src/esphome/components/pioneer/wyt_climate.h:4,
                 from src/esphome/components/pioneer/wyt_climate.cpp:1:
src/esphome/components/pioneer/wyt_remote.h:5:10: fatal error: esphome/components/remote_base/pioneer_wyt_protocol.h: No such file or directory
    5 | #include "esphome/components/remote_base/pioneer_wyt_protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/familyroom-heatpump/src/esphome/components/pioneer/wyt_climate.cpp.o] Error 1

**Comment by mikesmitty** [comment]
Ok, should be all set now. I realized you probably don't have a remote transmitter configured which is why you were getting those errors and I wasn't. Sorted out the ifdefs and and now it's compiling cleanly for both use-cases

**Comment by jmerryman** [comment]
Just built a fresh ubuntu VM to test again - same error. 

I'm going to spend some more time tinkering with it, but it may be a difference between the way the dev environment is set up vs my vanilla esphome install? Not sure if there are other prerequisites that need to be installed in esphome in order for it to handle dependencies the way it should. I edited the source files to refer to "src/esphome/components/remote_base/pioneer_wyt_protocol.h" instead of "esphome/components/remote_base/pioneer_wyt_protocol.h", which appears to clear that error, but then I get an error about binary_sensor.h:

In file included from src/esphome/components/pioneer/wyt_climate.cpp:6:
src/esphome/components/pioneer/wyt_climate.h:8:10: fatal error: esphome/components/binary_sensor/binary_sensor.h: No such file or directory
 #include "esphome/components/binary_sensor/binary_sensor.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/familyroom-heatpump/src/esphome/components/pioneer/wyt_climate.cpp.o] Error 1


I see that file in my python install, but they're not in the build directory inside .esphome

./venv/lib/python3.12/site-packages/esphome/components/nfc/binary_sensor/binary_sensor.h
./venv/lib/python3.12/site-packages/esphome/components/binary_sensor/binary_sensor.h

(venv) jmerryman@esphome-test:~$ ls .esphome/build/familyroom-heatpump/src/esphome/components/
api  captive_portal  climate  esp32  esp8266  esphome  logger  md5  mdns  network  ota  pioneer  preferences  safe_mode  sensor  socket  uart  web_server_base  wifi

**Comment by jmerryman** [comment]
OK - very weird, finally got it working. The solve was to add a binary_sensor to the yaml, which seems to force esphome to include that component in the build env. I confirmed that removing this causes the error, and putting it back fixes it. This is also confirmed working on command-line esphome and within Home Assistant

binary_sensor:
  - platform: homeassistant
    name: "Input Boolean From Home Assistant"
    entity_id: input_boolean.state_home

**Comment by mikesmitty** [comment]
Oh interesting. I'll need to add some logic around that. Thanks for the testing btw, much appreciated

**Comment by mikesmitty** [comment]
Ok, should be good now
